# Generated by Django 4.0.5 on 2022-12-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contracttemplate_entrollment_alter_student_customer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrollment',
            unique_together={('customer', 'classgrade')},
        ),
    ]
