# Generated by Django 4.0.5 on 2022-12-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_entrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='id_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
    ]
