# Generated by Django 4.0.5 on 2022-12-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_userprofile_user_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
