# Generated by Django 4.0.5 on 2022-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='123@qq.com', max_length=255, null=True, verbose_name='email address'),
        ),
    ]
