# Generated by Django 4.0.5 on 2022-12-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_userprofile_groups_userprofile_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
