# Generated by Django 4.0.5 on 2022-12-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_rename_is_admin_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('table_obj_list', '可以允许xx吃橘子'),)},
        ),
    ]
